version: "3.8"
services:
  web:
    image: crystallang/crystal:0.35.1
    command: crystal run src/twiliosim.cr
    ports:
      - 3000
    volumes:
      - .:/app
    working_dir: /app
  ngrok:
    image: wernight/ngrok
    ports:
      - 4040
    environment:
      NGROK_PORT: 'web:3000'
