version: "3.8"
services:
  web:
    image: crystallang/crystal:1.7-alpine
    command: crystal run src/twiliosim.cr
    expose:
      - "3000"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      LOG_LEVEL: trace
  ngrok:
    image: wernight/ngrok
    ports:
      - 4040
    environment:
      NGROK_PORT: 'web:3000'
